### PR TITLE
Fix compilation of Swift bindings

### LINKED ISSUE #736: Use C++ build artifacts in swift build system
Below are some issues and workarounds I encountered when trying to build otio-swift. I was working in Xcode 11.5 on macOS 10.15.4.

### issue
```
/Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/bridger.h:11:9: note: in file included from /Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/bridger.h:11:
#import "opentimelineio.h"
        ^
/Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/opentimelineio.h:9:9: note: in file included from /Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/opentimelineio.h:9:
#import "CxxAnyDictionaryMutationStamp.h"
        ^
/Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/CxxAnyDictionaryMutationStamp.h:11:9: note: in file included from /Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/CxxAnyDictionaryMutationStamp.h:11:
#import "CxxAny.h"
        ^
/Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/CxxAny.h:29:9: error: redefinition of 'BOOL'
        BOOL,
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/objc/objc.h:81:25: note: previous definition is here
    typedef signed char BOOL;
```

### workaround
Used refactor tool to rename `BOOL` to `BOOLEAN`

### issue
Lexical or Preprocessor Issue
'opentime/rationalTime.h' not found
rationalTime.h

Upon further investigation, the following paths were found in the "Header Search Paths" build settings for the target:
- `/Users/deb/Dropbox/build-otio/include`
- `/Users/deb/Dropbox/build-otio/include/opentimelineio/deps`

Other such pathing issues include:
- "Runpath search paths" - `/Users/deb/Dropbox/build-otio/lib`
- "Library search paths" - `/Users/deb/Dropbox/build-otio/lib`

Somehow the project would need to be updated to reference collected C++ library build products. Ideally we would have a way for the build system to generate x86_64 and arm64 binaries, lipo them together, and create products that could be used in building the Swift code.

## Additional Considerations
It feels like the swift bindings may be setup to use build products generated outside the the current tooling. The most friendly setup for consumers would likely be a separate repo set up to present a package for the [Swift Package Manager](https://swift.org/package-manager/).

### PR DESCRIPTION
**Pull request by meshula**
Fixes #736

**Summarize your change.**

- fixes conflicts with objc.h macro bool by using BOOL_ instead of BOOL. Arguably BOOLEAN is preferable to BOOL, but I'd prefer to address that in a separate PR.
- changes signing identity to "-" and team to none.
- Now looks for libopentime.dylib and libopentimelineio.dylib in /usr/local/lib. There should be a better way to handle this, but that is a fairly normal place to look for user dylibs.
- fixes a use of the to_string API which has changed

**Reference associated tests.**

The Swift bindings already have a great set of tests. Not all of them currently pass. In order to test yourself, libopentime.dylib and libopentimelineio.dylib must be place manually in the derived data folder. In my case, the necessary command was:

```sh
cp /usr/local/lib/*.dylib ~/Library/Developer/Xcode/DerivedData/otio-swift-akeblvbkhzdlqhdofukkdrtirvum/Build/Products/Debug
```

If anyone knows the right way to get the dylibs into the test, please LMK.

Currently the opentime bindings pass three quarters of the tests. opentinelineio fails immediately in a clone operation, and so none of the tests run.

### CODE REVIEW

**Review by davidbaraff — APPROVED** [review]
Looks good to me.

**Review by ssteinbach — APPROVED** [review]

**Review by reinecke — APPROVED** [review]
Great start to getting Swift bindings back in the mix!

**Comment by jchen9** [comment]
There's this old WIP pull request: https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/508

It has an `OTIO-Swift.framework` target, which would build & embed dylibs inside the framework. With it, you could set test target depending on and linking to it.

It was based on the old cxx branch but there could still be something useful... :)

**Comment by meshula** [comment]
@jchen9 Ah, cool! A PR yet to be submitted moves the Swift bindings into its own repo. The new repo would be a great opportunity to introduce the Swift demo app and other goodies you included with #508!

**Review by jminor — APPROVED** [review]
