### ISSUE TITLE
module level dunder names not appearing in __init__.py

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#1250]
## Bug Report

```
Python 3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 16:02:23) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import opentimelineio as otio
>>> otio.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'opentimelineio' has no attribute '__version__'
```

This is a regression from 0.14, see here: https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/1224

## Expected Behavior

[Description of the expected behavior.
](https://peps.python.org/pep-0008/#module-level-dunder-names)

**Comment by JeanChristopheMorinPerso** [comment]
The regression is caused by https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/1238.

**Comment by meshula** [comment]
Per @JeanChristopheMorinPerso: https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/1238 is the culprit I think. build_py runs before build_ext.

**Comment by meshula** [comment]
As part of a fix, let's add a test if possible, that the module level dunder names exist.

**Comment by JeanChristopheMorinPerso** [comment]
@meshula if you want you can assign this one to me. I can take care of it.

**Comment by meshula** [comment]
Thank you, that would be wonderful ~ I'm a bit slammed today!

**Comment by JeanChristopheMorinPerso** [comment]
Pull request created, but without tests. Testing that would either require to have PySide installed or we would have to parse the files which I feel is dirty...
