### ISSUE TITLE
Use C++ build artifacts in swift build system

### ISSUE THREAD

**Issue by reinecke** [PixarAnimationStudios/OpenTimelineIO#736]
Below are some issues and workarounds I encountered when trying to build otio-swift. I was working in Xcode 11.5 on macOS 10.15.4.

### issue
```
/Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/bridger.h:11:9: note: in file included from /Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/bridger.h:11:
#import "opentimelineio.h"
        ^
/Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/opentimelineio.h:9:9: note: in file included from /Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/opentimelineio.h:9:
#import "CxxAnyDictionaryMutationStamp.h"
        ^
/Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/CxxAnyDictionaryMutationStamp.h:11:9: note: in file included from /Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/CxxAnyDictionaryMutationStamp.h:11:
#import "CxxAny.h"
        ^
/Users/eric/Projects/OpenTimelineIO/src/swift-opentimelineio/CxxAny.h:29:9: error: redefinition of 'BOOL'
        BOOL,
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/objc/objc.h:81:25: note: previous definition is here
    typedef signed char BOOL;
```

### workaround
Used refactor tool to rename `BOOL` to `BOOLEAN`

### issue
Lexical or Preprocessor Issue
'opentime/rationalTime.h' not found
rationalTime.h

Upon further investigation, the following paths were found in the "Header Search Paths" build settings for the target:
- `/Users/deb/Dropbox/build-otio/include`
- `/Users/deb/Dropbox/build-otio/include/opentimelineio/deps`

Other such pathing issues include:
- "Runpath search paths" - `/Users/deb/Dropbox/build-otio/lib`
- "Library search paths" - `/Users/deb/Dropbox/build-otio/lib`

Somehow the project would need to be updated to reference collected C++ library build products. Ideally we would have a way for the build system to generate x86_64 and arm64 binaries, lipo them together, and create products that could be used in building the Swift code.

## Additional Considerations
It feels like the swift bindings may be setup to use build products generated outside the the current tooling. The most friendly setup for consumers would likely be a separate repo set up to present a package for the [Swift Package Manager](https://swift.org/package-manager/).

**Comment by meshula** [comment]
The Swift Package Manager is available to Xcode users as of Xcode 11. It's a reasonable question as to whether Xcode 11 is a minimum requirement for the bindings. I wonder if the bindings can be build via Cmake? If so, the trickiness of pointing the xcodeproj to the Cmake install target could be quietly side-stepped.

**Comment by davidbaraff** [comment]
Bringing libraries into my projects via SPM is the option I like best when it is available.
Requiring Xcode 11 for OTIO swift bindings seems to me an utterly low bar to ask people to step over.  Good idea.
